language: scala
dist: trusty
sudo: false

cache:
  directories:
    $HOME/.ivy2
    $HOME/.sbt

git:
  depth: 10

env:
  global:
    SBT_ARGS="-Dsbt.log.noformat=true"

jobs:
  include:
    - stage: test
      script: sbt $SBT_ARGS test
    -
      script: sbt $SBT_ARGS run
